version: '3.8'
services:
  api:
    container_name: burger-api
    restart: always
    build: .
    environment:
      - PORT=${PORT}
      - DB_URI=${DB_URI}
    ports:
    - '3000:3000'
    depends_on:
    - mongodb
    networks:
    - burger
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB} 
    networks:
      - burger
networks:
  burger:
    driver: bridge